apiVersion: v1
kind: Service
metadata:
  name: redis-node-sidi-service
spec:
  selector:
    app: node-redis-sidi
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer


apiVersion: v1
kind: Service
metadata:
  name: redis-sidi-service
spec:
  selector:
    app: redis-sidi
  ports:
    - port: 6379
      targetPort: 6379
  type: LoadBalancer
